// import './modules/createElement.spec'
// import './modules/util.spec'
// import './modules/style.spec'

// import './modules/classInherit.spec'
// import './modules/shallow.spec'
// import './modules/browser.spec'
// import './modules/cloneElement.spec'
//import './__test__/ReactComponent-test.js'
//import './__test__/ReactComponentLifeCycle-test.js'
// import './__test__/ReactCompositeComponentNestedState-test.js'
// import './__test__/ReactCompositeComponentState-test.js'
// import './__test__/ReactIdentity-test.js'
// import './__test__/refs-test.js'
import './__test__/LifeCycle-test.js'